### ISSUE TITLE
missing visualization.launch file in the repo

### ISSUE THREAD

**Issue by onurbagoren** [ethz-asl/virus_nerf#4]
Hello,

I have been able to reformat a custom dataset and want to visualize it using the last step as described in the [Dataset Collection](https://github.com/ethz-asl/virus_nerf?tab=readme-ov-file#dataset-collection-1) section. Unfortunately, it seems like the `sensors/Launch/visualization.launch` file seems to be missing. Would you mind sharing that or explaining what the contents are so that we can write an equivalent of it?

**Comment by nas-git-nas** [comment]
That is great!
I added the visualization launch file. It can be used to verify the data pre-processing.
